using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;
using System.Linq;
using System.Threading.Tasks;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace AssetManager.My.Resources
{

	//This class was auto-generated by the StronglyTypedResourceBuilder
	//class via a tool like ResGen or Visual Studio.
	//To add or remove a member, edit your .ResX file then rerun ResGen
	//with the /str option, or rebuild your VS project.
	///<summary>
	///  A strongly-typed resource class, for looking up localized strings, etc.
	///</summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
	public static class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		///<summary>
		///  Returns the cached ResourceManager instance used by this class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssetManager.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		///<summary>
		///  Overrides the current thread's CurrentUICulture property for all
		///  resource lookups using this strongly typed resource class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap AddIcon {
			get {
				object obj = ResourceManager.GetObject("AddIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap AddNoteIcon {
			get {
				object obj = ResourceManager.GetObject("AddNoteIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap AdminIcon {
			get {
				object obj = ResourceManager.GetObject("AdminIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap AssetManagerIcon {
			get {
				object obj = ResourceManager.GetObject("AssetManagerIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap CascadeIcon {
			get {
				object obj = ResourceManager.GetObject("CascadeIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap CheckedBoxGreenIcon {
			get {
				object obj = ResourceManager.GetObject("CheckedBoxGreenIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap CheckedBoxIcon {
			get {
				object obj = ResourceManager.GetObject("CheckedBoxIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap CheckedBoxRedIcon {
			get {
				object obj = ResourceManager.GetObject("CheckedBoxRedIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Byte[].
		///</summary>
		public static byte[] CheckForTVRegistryValue {
			get {
				object obj = ResourceManager.GetObject("CheckForTVRegistryValue", resourceCulture);
				return Convert.ToByte(obj);
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap CheckOutIcon {
			get {
				object obj = ResourceManager.GetObject("CheckOutIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap ChromeIcon {
			get {
				object obj = ResourceManager.GetObject("ChromeIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap CloseCancelDeleteIcon {
			get {
				object obj = ResourceManager.GetObject("CloseCancelDeleteIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap CopyIcon {
			get {
				object obj = ResourceManager.GetObject("CopyIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap DeleteIcon {
			get {
				object obj = ResourceManager.GetObject("DeleteIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap DeleteRedIcon {
			get {
				object obj = ResourceManager.GetObject("DeleteRedIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap DetailsIcon {
			get {
				object obj = ResourceManager.GetObject("DetailsIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap EditIcon {
			get {
				object obj = ResourceManager.GetObject("EditIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Byte[].
		///</summary>
		public static byte[] Exh_K_01_Asset_Input_Formnew {
			get {
				object obj = ResourceManager.GetObject("Exh_K_01_Asset_Input_Formnew", resourceCulture);
				return Convert.ToByte(obj);
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Byte[].
		///</summary>
		public static byte[] Exh_K_02_Asset_Disposal_Form {
			get {
				object obj = ResourceManager.GetObject("Exh_K_02_Asset_Disposal_Form", resourceCulture);
				return Convert.ToByte(obj);
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Byte[].
		///</summary>
		public static byte[] Exh_K_03_Asset_Transfer_Form {
			get {
				object obj = ResourceManager.GetObject("Exh_K_03_Asset_Transfer_Form", resourceCulture);
				return Convert.ToByte(obj);
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap FolderIcon {
			get {
				object obj = ResourceManager.GetObject("FolderIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap FormIcon {
			get {
				object obj = ResourceManager.GetObject("FormIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap GK__UpdateIcon {
			get {
				object obj = ResourceManager.GetObject("GK__UpdateIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap GK_SmallIcon {
			get {
				object obj = ResourceManager.GetObject("GK_SmallIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		///</summary>
		public static System.Drawing.Icon icon_box {
			get {
				object obj = ResourceManager.GetObject("icon_box", resourceCulture);
				return (System.Drawing.Icon)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap ImportIcon {
			get {
				object obj = ResourceManager.GetObject("ImportIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		///</summary>
		public static System.Drawing.Icon inventory_icon_orange {
			get {
				object obj = ResourceManager.GetObject("inventory_icon_orange", resourceCulture);
				return (System.Drawing.Icon)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap LoadingAni {
			get {
				object obj = ResourceManager.GetObject("LoadingAni", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap MoneyCircle2Icon {
			get {
				object obj = ResourceManager.GetObject("MoneyCircle2Icon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap PaperClipIcon {
			get {
				object obj = ResourceManager.GetObject("PaperClipIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap PauseIcon {
			get {
				object obj = ResourceManager.GetObject("PauseIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap PlayIcon {
			get {
				object obj = ResourceManager.GetObject("PlayIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap RDPIcon {
			get {
				object obj = ResourceManager.GetObject("RDPIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap RefreshIcon {
			get {
				object obj = ResourceManager.GetObject("RefreshIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap RestartIcon {
			get {
				object obj = ResourceManager.GetObject("RestartIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap SearchIcon {
			get {
				object obj = ResourceManager.GetObject("SearchIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap SibiIcon {
			get {
				object obj = ResourceManager.GetObject("SibiIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap TeamViewerIcon {
			get {
				object obj = ResourceManager.GetObject("TeamViewerIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap Title_Text_Orange {
			get {
				object obj = ResourceManager.GetObject("Title_Text_Orange", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap TransferArrowsIcon {
			get {
				object obj = ResourceManager.GetObject("TransferArrowsIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Drawing.Bitmap.
		///</summary>
		public static System.Drawing.Bitmap TrashIcon {
			get {
				object obj = ResourceManager.GetObject("TrashIcon", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		///<summary>
		///  Looks up a localized resource of type System.Byte[].
		///</summary>
		public static byte[] UpdateChrome {
			get {
				object obj = ResourceManager.GetObject("UpdateChrome", resourceCulture);
				return Convert.ToByte(obj);
			}
		}
	}
}
